hostname: k3s-master-1
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCb7fcDZfIG+SxuP5UsZaoHPdh9MNxtEL5xRI71hzMS5h4SsZiPGEP4shLcF9YxSncdOJpyOJ6OgumNSFWj2pCd/kqg9wQzk/E1o+FRMbWX5gX8xMzPig8mmKkW5szhnP+yYYYuGUqvTAKX4ua1mQwL6PipWKYJ1huJhgpGHrvSQ6kuywJ23hw4klcaiZKXVYtvTi8pqZHhE5Kx1237a/6GRwnbGLEp0UR2Q/KPf6yRgZIrCdD+AtOznSBsBhf5vqcfnnwEIC/DOnqcOTahBVtFhOKuPSv3bUikAD4Vw7SIRteMltUVkd/O341fx+diKOBY7a8M6pn81HEZEmGsr7rT sam@SamMac.local
rancher:
  console: ubuntu
  resize_device: /dev/sda
  docker:
    tls: true
  network:
    post_cmds:
      - dhcpcd -e force_hostname=true eth0
    dns:
      nameservers:
        - 8.8.8.8
        - 1.1.1.1
    interfaces:
      eth0:
        address: 192.168.1.81/32
        netmask: 255.255.255.0
        gateway: 192.168.1.1
        mtu: 1400
        dhcp: false
      lo:
        address: 127.0.0.1/8