apiVersion: v1
kind: ServiceAccount
metadata:
  name: super-user
  namespace: default

---

apiVersion: v1
kind: Secret
metadata:
  name: super-user-secret
  namespace: default
  annotations:
    kubernetes.io/service-account.name: super-user
type: kubernetes.io/service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: super-user-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: super-user-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: super-user-role
subjects:
- kind: ServiceAccount
  name: super-user
  namespace: default
